---
# Console logger
- descriptor: "pip-services-commons:logger:console:*:*"
  level: "trace"

# People persistence
- descriptor: "pip-services-biometry:persistence:memory:people:*"

# People controller
- descriptor: "pip-services-biometry:controller:*:people:*"

# Echo rest service
- descriptor: "pip-services-biometry:service:rest:people:*"
  connection:
    protocol: "http"
    host: "0.0.0.0"