---
# Console logger
- descriptor: "pip-services-commons:logger:console:*:*"
  level: "trace"

# Biometry persistence
- descriptor: "pip-services-biometry:persistence:memory:biometry:*"

# Biometry controller
- descriptor: "pip-services-biometry:controller:*:biometry:*"

# Biometry rest service
- descriptor: "pip-services-biometry:service:rest:biometry:*"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: "3001"
